#ifndef SWITCH_H
#define SWITCH_H

typedef enum { VE_POS_PREPRESSED, VE_POS_PRESSED, VE_POS_PRERELEASED, VE_POS_RELEASED,
               VE_NEG_PREPRESSED, VE_NEG_PRESSED, VE_NEG_PRERELEASED, VE_NEG_RELEASED,
               P_SWCH_PREPRESSED, P_SWCH_PRESSED, P_SWCH_PRERELEASED, P_SWCH_RELEASED } SWITCH_STATE_t;

#endif
