/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSWITCH_H
#define _MOCKSWITCH_H

#include "../unity/unity.h"
#include "../../source/switch/switch.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockswitch_Init(void);
void Mockswitch_Destroy(void);
void Mockswitch_Verify(void);




#define SW_GetName_ExpectAndReturn(cmock_retval) SW_GetName_CMockExpectAndReturn(__LINE__, cmock_retval)
void SW_GetName_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, t_SWITCH cmock_to_return);
#define SW_GetState_ExpectAndReturn(cmock_retval) SW_GetState_CMockExpectAndReturn(__LINE__, cmock_retval)
void SW_GetState_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, t_SWITCH_STATE cmock_to_return);
#define SW_GetDuration_ExpectAndReturn(cmock_retval) SW_GetDuration_CMockExpectAndReturn(__LINE__, cmock_retval)
void SW_GetDuration_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
