/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "../cmock/cmock.h"
#include "Mockswitch.h"

static const char* CMockString_SW_GetDuration = "SW_GetDuration";
static const char* CMockString_SW_GetName = "SW_GetName";
static const char* CMockString_SW_GetState = "SW_GetState";

typedef struct _CMOCK_SW_GetName_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  t_SWITCH ReturnVal;

} CMOCK_SW_GetName_CALL_INSTANCE;

typedef struct _CMOCK_SW_GetState_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  t_SWITCH_STATE ReturnVal;

} CMOCK_SW_GetState_CALL_INSTANCE;

typedef struct _CMOCK_SW_GetDuration_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_SW_GetDuration_CALL_INSTANCE;

static struct MockswitchInstance
{
  CMOCK_MEM_INDEX_TYPE SW_GetName_CallInstance;
  CMOCK_MEM_INDEX_TYPE SW_GetState_CallInstance;
  CMOCK_MEM_INDEX_TYPE SW_GetDuration_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockswitch_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.SW_GetName_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SW_GetName);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SW_GetState_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SW_GetState);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SW_GetDuration_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SW_GetDuration);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockswitch_Init(void)
{
  Mockswitch_Destroy();
}

void Mockswitch_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

t_SWITCH SW_GetName(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SW_GetName_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SW_GetName);
  cmock_call_instance = (CMOCK_SW_GetName_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SW_GetName_CallInstance);
  Mock.SW_GetName_CallInstance = CMock_Guts_MemNext(Mock.SW_GetName_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void SW_GetName_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, t_SWITCH cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SW_GetName_CALL_INSTANCE));
  CMOCK_SW_GetName_CALL_INSTANCE* cmock_call_instance = (CMOCK_SW_GetName_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SW_GetName_CallInstance = CMock_Guts_MemChain(Mock.SW_GetName_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(t_SWITCH[sizeof(cmock_to_return) == sizeof(t_SWITCH) ? 1 : -1])); /* add t_SWITCH to :treat_as_array if this causes an error */
}

t_SWITCH_STATE SW_GetState(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SW_GetState_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SW_GetState);
  cmock_call_instance = (CMOCK_SW_GetState_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SW_GetState_CallInstance);
  Mock.SW_GetState_CallInstance = CMock_Guts_MemNext(Mock.SW_GetState_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void SW_GetState_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, t_SWITCH_STATE cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SW_GetState_CALL_INSTANCE));
  CMOCK_SW_GetState_CALL_INSTANCE* cmock_call_instance = (CMOCK_SW_GetState_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SW_GetState_CallInstance = CMock_Guts_MemChain(Mock.SW_GetState_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(t_SWITCH_STATE[sizeof(cmock_to_return) == sizeof(t_SWITCH_STATE) ? 1 : -1])); /* add t_SWITCH_STATE to :treat_as_array if this causes an error */
}

uint8_t SW_GetDuration(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SW_GetDuration_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SW_GetDuration);
  cmock_call_instance = (CMOCK_SW_GetDuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SW_GetDuration_CallInstance);
  Mock.SW_GetDuration_CallInstance = CMock_Guts_MemNext(Mock.SW_GetDuration_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void SW_GetDuration_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SW_GetDuration_CALL_INSTANCE));
  CMOCK_SW_GetDuration_CALL_INSTANCE* cmock_call_instance = (CMOCK_SW_GetDuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SW_GetDuration_CallInstance = CMock_Guts_MemChain(Mock.SW_GetDuration_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

